{{- range .Values.externalSecrets}}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
spec:
  # SecretStoreRef defines which SecretStore to use when fetching the secret data
  secretStoreRef:
    name: {{ .secretStore }}
    kind: ClusterSecretStore  # or ClusterSecretStore
  refreshInterval: "2h"
  data: {{ toYaml .data | nindent 4 }}
  target:
    creationPolicy: Owner
    template:
      {{- with .template }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
---
{{- end }}
