apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterissuer.name }}
spec:
  acme:
    server: {{ .Values.clusterissuer.server }}
    email: {{ .Values.clusterissuer.email }}
    solvers:
{{ toYaml .Values.clusterissuer.solvers | indent 4 }}
    privateKeySecretRef:
      name: {{ .Values.clusterissuer.name }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.clusterissuer.name }}-staging
spec:
  acme:
    server: "https://acme-staging-v02.api.letsencrypt.org/directory"
    email: {{ .Values.clusterissuer.email }}
    solvers:
{{ toYaml .Values.clusterissuer.solvers | indent 4 }}
    privateKeySecretRef:
      name: {{ .Values.clusterissuer.name }}-staging
