{{- define "example-std-lib.external-secrets" -}}
{{- range $secret := .Values.externalSecrets }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ tpl (toYaml $secret.name) $ }}
  labels: {{- include "example.labels" $ | nindent 4 }}
  {{- with $secret.externalSecretsAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  secretStoreRef:
    name: {{ $secret.clusterSecretStore }}
    kind: ClusterSecretStore
  refreshInterval: {{ $secret.refreshInterval }}
  target:
    creationPolicy: Owner
    template:
      metadata:
      {{- with $secret.annotations }}
        annotations:
          {{- toYaml . | nindent 10 }}
      {{- end }}
      {{- with $secret.labels }}
        labels:
          {{- toYaml . | nindent 10 }}
      {{- end }}
      {{- with $secret.data }}
      data:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  data:
    {{- toYaml $secret.refs | nindent 4 }}
---
{{- end }}
{{- end }}