---
{{ range .Values.extraServiceAccounts }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
{{- if .annotations }}
  annotations: {{ toYaml .annotations | nindent 4 }}
{{- end }}
{{- if .labels }}
  labels: {{ toYaml .labels | nindent 4 }}
{{- end }}
{{- end -}}
